### ISSUE TITLE
[Client] [FEAT] Common UI Component 작업

### ISSUE THREAD

**Issue by jhsung23** [codestates-seb/seb44_pre_037#34]
## 요구사항 ID
SET-006

## 요구사항
Common UI Component 작업

## 상세 요구사항
프로젝트 전반적으로 사용할 컴포넌트 작업

## TODO
- [ ] 버튼 (Ask Question, Submit)
- [ ] 알럿
- [ ] 툴팁
- [ ] 태그

**Comment by hyeincha** [comment]
tag도 atom으로 구현되면 좋을 것 같습니다 !

**Comment by jhsung23** [comment]
> tag도 atom으로 구현되면 좋을 것 같습니다 !

반영했습니다~
